main: me.waqe.plugin.App
name: PlayerVaults
version: '0.1'
api: '1'
api-version: 1.16

commands:
  version:
    description: Plugin version
    usage: /version
  playervault:
    description: Private Vaults
    usage: /playervault
    aliases: pv